export const ExampleCompany = {
  value: 'ООО "ЛУК-ОИЛ37"',
  unrestricted_value: 'ООО "ЛУК-ОИЛ37"',
  data: {
    kpp: '781101001',
    capital: null,
    management: {
      name: 'Дубкова Екатерина Вячеславовна',
      post: 'ГЕНЕРАЛЬНЫЙ ДИРЕКТОР',
      disqualified: null,
    },
    founders: null,
    managers: null,
    predecessors: null,
    successors: null,
    branch_type: 'MAIN',
    branch_count: 2,
    source: null,
    qc: null,
    hid: '857189adc39c5647ebe66410e0df545d376c67b6c69637e3a62917dee5deb09f',
    type: 'LEGAL',
    state: {
      status: 'LIQUIDATED',
      code: '415',
      actuality_date: 1634774400000,
      registration_date: 1453161600000,
      liquidation_date: 1634774400000,
    },
    opf: {
      type: '2014',
      code: '12300',
      full: 'Общество с ограниченной ответственностью',
      short: 'ООО',
    },
    name: {
      full_with_opf: 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ЛУК-ОИЛ37"',
      short_with_opf: 'ООО "ЛУК-ОИЛ37"',
      latin: null,
      full: 'ЛУК-ОИЛ37',
      short: 'ЛУК-ОИЛ37',
    },
    inn: '7811272520',
    ogrn: '1167847057091',
    okpo: '34353017',
    okato: '40285000000',
    oktmo: '40378000000',
    okogu: '4210014',
    okfs: '16',
    okved: '81.22',
    okveds: null,
    authorities: null,
    documents: null,
    licenses: null,
    finance: {
      tax_system: null,
      income: null,
      expense: null,
      debt: null,
      penalty: null,
      year: null,
    },
    address: {
      value:
        '192019, ГОРОД САНКТ-ПЕТЕРБУРГ, УЛ. ПРОФЕССОРА КАЧАЛОВА, Д. 7, ЛИТЕР А, ПОМЕЩ. 11-Н ЧАСТЬ ПОМ. 6 (ОФИС 218)',
      unrestricted_value:
        '192019, ГОРОД САНКТ-ПЕТЕРБУРГ, УЛ. ПРОФЕССОРА КАЧАЛОВА, Д. 7, ЛИТЕР А, ПОМЕЩ. 11-Н ЧАСТЬ ПОМ. 6 (ОФИС 218)',
      data: {
        postal_code: '192019',
        country: 'Россия',
        country_iso_code: 'RU',
        federal_district: 'Северо-Западный',
        region_fias_id: 'c2deb16a-0330-4f05-821f-1d09c93331e6',
        region_kladr_id: '7800000000000',
        region_iso_code: 'RU-SPE',
        region_with_type: 'г Санкт-Петербург',
        region_type: 'г',
        region_type_full: 'город',
        region: 'Санкт-Петербург',
        area_fias_id: null,
        area_kladr_id: null,
        area_with_type: null,
        area_type: null,
        area_type_full: null,
        area: null,
        city_fias_id: 'c2deb16a-0330-4f05-821f-1d09c93331e6',
        city_kladr_id: '7800000000000',
        city_with_type: 'г Санкт-Петербург',
        city_type: 'г',
        city_type_full: 'город',
        city: 'Санкт-Петербург',
        city_area: null,
        city_district_fias_id: null,
        city_district_kladr_id: null,
        city_district_with_type: 'Невский р-н',
        city_district_type: 'р-н',
        city_district_type_full: 'район',
        city_district: 'Невский',
        settlement_fias_id: null,
        settlement_kladr_id: null,
        settlement_with_type: null,
        settlement_type: null,
        settlement_type_full: null,
        settlement: null,
        street_fias_id: '0e553a9e-713c-43cc-a062-ae38544ed074',
        street_kladr_id: '78000000000114800',
        street_with_type: 'ул Профессора Качалова',
        street_type: 'ул',
        street_type_full: 'улица',
        street: 'Профессора Качалова',
        house_fias_id: '19411e90-e058-41fa-9783-2507d0204c94',
        house_kladr_id: '7800000000011480100',
        house_cadnum: null,
        house_type: 'д',
        house_type_full: 'дом',
        house: '7',
        block_type: 'литера',
        block_type_full: 'литера',
        block: 'а',
        entrance: null,
        floor: null,
        flat_fias_id: null,
        flat_cadnum: null,
        flat_type: 'помещ',
        flat_type_full: 'помещение',
        flat: '11Н',
        flat_area: null,
        square_meter_price: null,
        flat_price: null,
        postal_box: null,
        fias_id: '19411e90-e058-41fa-9783-2507d0204c94',
        fias_code: '78000000000000011480100',
        fias_level: '8',
        fias_actuality_state: '0',
        kladr_id: '7800000000011480100',
        geoname_id: '498817',
        capital_marker: '0',
        okato: '40285561000',
        oktmo: '40378000',
        tax_office: '7811',
        tax_office_legal: '7811',
        timezone: 'UTC+3',
        geo_lat: '59.91461',
        geo_lon: '30.394587',
        beltway_hit: 'IN_KAD',
        beltway_distance: null,
        metro: [
          {
            name: 'Площадь Александра Невского 2',
            line: 'Правобережная',
            distance: 1.2,
          },
          {
            name: 'Площадь Александра Невского 1',
            line: 'Невско-Василеостровская',
            distance: 1.2,
          },
          {
            name: 'Новочеркасская',
            line: 'Правобережная',
            distance: 1.9,
          },
        ],
        qc_geo: '1',
        qc_complete: null,
        qc_house: null,
        history_values: null,
        unparsed_parts: null,
        source:
          '192019, ГОРОД САНКТ-ПЕТЕРБУРГ, УЛ. ПРОФЕССОРА КАЧАЛОВА, Д. 7, ЛИТЕР А, ПОМЕЩ. 11-Н ЧАСТЬ ПОМ. 6 (ОФИС 218)',
        qc: '1',
      },
    },
    phones: null,
    emails: null,
    ogrn_date: 1453161600000,
    okved_type: '2014',
    employee_count: null,
  },
};
export const ExampleFullCompany = {
  bank: {
    bank: 'string',
    bankAddress: 'string',
    bik: 'string',
    correspondent: 'string',
    payment: 'string',
  },
  object: 'company',
  client: ['string'],
  companyLocation:
    '192019, ГОРОД САНКТ-ПЕТЕРБУРГ, УЛ. ПРОФЕССОРА КАЧАЛОВА, Д. 7, ЛИТЕР А, ПОМЕЩ. 11-Н ЧАСТЬ ПОМ. 6 (ОФИС 218)',
  employeesCount: 0,
  factLocation:
    '192019, ГОРОД САНКТ-ПЕТЕРБУРГ, УЛ. ПРОФЕССОРА КАЧАЛОВА, Д. 7, ЛИТЕР А, ПОМЕЩ. 11-Н ЧАСТЬ ПОМ. 6 (ОФИС 218)',
  fax: 'string',
  name: 'ООО "ЛУК-ОИЛ37"',
  ownership: 'ООО',
  permissions: {},
  phoneNumber: 'string',
  phones: ['string'],
  postLocation:
    '192019, ГОРОД САНКТ-ПЕТЕРБУРГ, УЛ. ПРОФЕССОРА КАЧАЛОВА, Д. 7, ЛИТЕР А, ПОМЕЩ. 11-Н ЧАСТЬ ПОМ. 6 (ОФИС 218)',
  requisites: ExampleCompany,
};
